#pragma once
enum class CommandListType
{
	GRAPHICS = D3D12_COMMAND_LIST_TYPE_DIRECT,
	COPY = D3D12_COMMAND_LIST_TYPE_COPY,
	COMPUTE = D3D12_COMMAND_LIST_TYPE_COMPUTE
};

enum class DescriptorHeapTypes
{
	RENDERTARGET_VIEW = D3D12_DESCRIPTOR_HEAP_TYPE_RTV,
	DEPTHSTENCIL_VIEW = D3D12_DESCRIPTOR_HEAP_TYPE_DSV,
	SHADERBINDABLE_VIEW = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV
};

enum class ResourceState
{
	COMMON = D3D12_RESOURCE_STATE_COMMON,
	COPY_DEST = D3D12_RESOURCE_STATE_COPY_DEST,
	COPY_SOURCE = D3D12_RESOURCE_STATE_COPY_SOURCE,
	DEPTH_WRITE = D3D12_RESOURCE_STATE_DEPTH_WRITE,
	RENDER_TARGET = D3D12_RESOURCE_STATE_RENDER_TARGET,
	PRESENT = D3D12_RESOURCE_STATE_PRESENT,
	VERTEX_AND_CONSTANT_BUFFER = D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER
};

enum class ShaderVisibility
{
	VERTEX = D3D12_SHADER_VISIBILITY_VERTEX,
	PIXEL = D3D12_SHADER_VISIBILITY_PIXEL,
};

enum class ShaderType
{
	VERTEX,
	PIXEL,
};